### ISSUE TITLE
Google Site Search will stop working on Apr 21 and we will be downgraded to an ad-supported Custom Search Engine

### ISSUE THREAD

**Issue by bradical** [hannonhill/Website#1]
Wasn't sure the best place to park this but wanted to keep track of it.

> Thanks for mailing Google Enterprise Search Support Team.
> I would like to update you that we are winding down the Google Site Search product over the course of the next year. We will continue to support all active
customers through the end of their license terms. Starting April 1, 2017, no new sales/renewals/upgrades will be available.
> Your paid GSS subscription "Hannon Hill Cascade CMS" expires on April 21, 2017. You will continue to receive support and maintenance through the duration of your contract i.e April 21, 2017. Once your search engine expires, there will be no "Renew" option available to renew your Search Engine and your search engine will be downgraded to a Free CSE engine where Ads will be displayed.
> When your GSS subscription expires or the quota is exhausted, it will automatically convert to Custom Search Engine (CSE). Custom Search Engine is ads-supported product providing similar capabilities to GSS, including the ability to build custom search engines for sites or pages, image search for your website, and customized look and feel of search results from the control panel and Ads will be displayed. The only alternative to GSS version is the Free CSE version with Ads being displayed.

@hannonhill/engineering @hannonhill/support @hannonhill/services

**Comment by rgriffith** [comment]
I found an article that lists some alternatives - http://www.cmswire.com/information-management/goodbye-google-site-search/

I think it's less "out of the box," but we could try out AWS' solution if we want to keep everything consolidated.

**Comment by dzello** [comment]
Have you guys thought about [Algolia](https://algolia.com/)? It's not out-of-the-box but I see you're working on Cascade CMS? So implementation should be easy for you and you could reuse the integration for other Cascade sites. 

Algolia has a blog post about [switching from GSS](https://blog.algolia.com/google-site-search-alternative/) that goes deeper. I'm happy to answer any questions you have too.
